Draft reusable workflow

diff --git a/.github/workflows/build_test_deploy.yml b/.github/workflows/build_test_deploy.yml
--- a/.github/workflows/build_test_deploy.yml
+++ b/.github/workflows/build_test_deploy.yml
@@ -1,111 +1,78 @@
-name: Deploy payu-dev conda environment
+name: Build, test and deploy conda env
 on:
-  schedule:
-   - cron: '0 21 * * *' # Runs every morning at 7AM AEST
-  workflow_dispatch: # Allows manual triggering
-  push:
-    branches:
-      - main
-    paths:
-      - 'environments/payu-dev/**' # Run when payu-dev environment is updated
+  workflow_call:
+    inputs:
+      environment:
+        description: "Environment to update"
+        required: true
+        type: string
+      deploy:
+        description: "Run deploy"
+        type: boolean
+        required: true
+      build_and_test:
+        description: "Run build and test PBS jobs"
+        type: boolean
+        required: true
+      
 jobs:
-  check_for_payu_updates:
-    name: Check for updates to payu-org/payu repository
-    runs-on: ubuntu-latest
-    outputs:
-      commits-count: ${{ steps.check-payu-commits.outputs.commits-count }}
-      last-commit-hash: ${{ steps.check-payu-commits.outputs.latest-commit-hash }}
-    steps:
-      - name: Checkout current repository
-        uses: actions/checkout@v4
-
-      - name: Get last workflow run time
-        id: last-run-time
-        env:
-          GH_TOKEN: ${{ secrets.GH_TOKEN }}
-        run: |
-          # Fetch the last successful workflow run time
-          last_run_time=$(gh run list --status success --workflow deploy_payu_dev.yml --json updatedAt --jq .[0].updatedAt)
-
-          echo "Last successful workflow run time: $last_run_time"
-          echo "last-run-time=$last_run_time" >> $GITHUB_OUTPUT
-
-      - name: Checkout payu repository
-        uses: actions/checkout@v4
-        with:
-          repository: payu-org/payu
-          path: payu
-          ref: master
-
-      - name: Check commits in payu repository
-        id: check-payu-commits
-        run: |
-          # Check for any commits since last successful runtime
-          last_run_time="${{ steps.last-run-time.outputs.last-run-time }}"
-          commits_count=$(git -C ./payu rev-list --count --since="$last_run_time" master)
-
-          # Get latest commit hash
-          latest_commit_hash=$(git -C ./payu rev-parse --short HEAD)
-
-          echo "::notice::Number of new commits since last run: $commits_count, latest commit hash: $latest_commit_hash"
-
-          echo "commits-count=$commits_count" >> $GITHUB_OUTPUT
-          echo "latest-commit-hash=$latest_commit_hash" >> $GITHUB_OUTPUT
-
-  build_base_image:
-    uses: ./.github/workflows/build_base_image.yml
-
-  # Need to modify environment configs file
-  # Could upload artefact of changed environment files?
-  # and download in generic job??
   build_test_and_deploy:
-    name: Build, test and deploy payu-dev
     runs-on: ubuntu-latest
-    needs:
-      - build_base_image
-      - check_for_payu_updates
-    # Deploy if manually triggered, payu environment files has been updated,
-    # or if there's new commits to payu repository
-    if: >
-      needs.check_for_payu_updates.outputs.commits-count > 0 ||
-      github.event_name == 'push' ||
-      github.event_name == 'workflow_dispatch'
     environment: Gadi
-    env:
-      environment: payu-dev
     steps:
-      - uses: actions/checkout@v4
+      - name: Check Gadi Github Environment configuration
+        run: |
+          vars_unset=false
+          if [ -z "${{ vars.ADMIN_DIR }}" ]; then
+            echo "::error::vars.ADMIN_DIR is unset. ADMIN_DIR is the base directory which will contain the staging and logs sub-directories"
+            vars_unset=true
+          fi
+          if [ -z "${{ vars.CONDA_BASE }}" ]; then
+            echo "::error::vars.CONDA_BASE is unset. CONDA_BASE is the base deployment directory which will contain apps and module sub-directories"
+            vars_unset=true
+          fi
+          if [ -z "${{ vars.PRERELEASE_ADMIN_DIR }}" ]; then
+            echo "::error::vars.PRERELEASE_ADMIN_DIR is unset. PRERELEASE_ADMIN_DIR is the prerelease base directory which will contain the staging and logs sub-directories"
+            vars_unset=true
+          fi
+          if [ -z "${{ vars.PRERELEASE_CONDA_BASE }}" ]; then
+            echo "::error::vars.PRERELEASE_CONDA_BASE is unset. PRERELEASE_CONDA_BASE is the prerelease base deployment directory which will contain apps and module sub-directories"
+            vars_unset=true
+          fi
+          if [ -z "${{ vars.PROJECT }}" ]; then
+            echo "::error::vars.PROJECT is unset. PROJECT is the project code passed to build+test qsub calls"
+            vars_unset=true
+          fi
+          if [ -z "${{ vars.STORAGE }}" ]; then
+            echo "::error::vars.STORAGE is unset. STORAGE is the storage flags passed to build+test qsub calls"
+            vars_unset=true
+          fi
+          if [ -z "${{ vars.APPS_USERS_GROUP }}" ]; then
+            echo "::error::vars.APPS_USERS_GROUP is unset. APPS_USERS_GROUP is used for setting file permissions"
+            vars_unset=true
+          fi
+          if [ -z "${{ vars.APPS_OWNER }}" ]; then
+            echo "::error::APPS_OWNER is unset. APPS_OWNER is used for setting file permissions"
+            vars_unset=true
+          fi
+          if [ -z "${{ secrets.REPO_PATH }}" ]; then
+            echo "::error::secrets.REPO_PATH is unset. REPO_PATH is the path where this repository is synced to"
+            vars_unset=true
+          fi
+          if [ -z "${{ vars.PRERELEASE_ENVIRONMENTS }}" ]; then
+            echo "::error::vars.PRERELEASE_ENVIRONMENTS is unset. PRERELEASE_ENVIRONMENTS is the list of environments to deploy to prerelease directories"
+            vars_unset=true
+          fi
 
-      - name: Download base container
-        uses: actions/download-artifact@v4
-        with:
-            name: base-container
-            path: container
-
-      - name: Get Payu Version
-        id: payu
-        run: |
-          # Set version to datetime and last short commit hash of payu
-          NOW=$(date -u +"%Y%m%dT%H%M%SZ")
-          COMMIT_HASH=${{ needs.check_for_payu_updates.outputs.last-commit-hash }}
-          VERSION="dev-$NOW-$COMMIT_HASH"
-          echo "version=$VERSION" >> $GITHUB_OUTPUT
-      
-      - name: Update Environment file
-        run: |
-          # Replace payu commit hash in environment file with latest commit hash
-          PAYU_URL="git+https://github.com/payu-org/payu.git"
-          sed -i "s|$PAYU_URL@.*$|$PAYU_URL@${{ needs.check_for_payu_updates.outputs.last-commit-hash }}|g" environments/payu-dev/environment.yml
-      
-      - name: Update Version in config file
-        run: |
-          # Update VERSION_TO_MODIFY in payu-dev config file
-          sed -i "s|^export VERSION_TO_MODIFY=.*$|export VERSION_TO_MODIFY=${{ steps.payu.outputs.version }}|g" environments/payu-dev/config.sh
+          if [ "$vars_unset" == "true" ]; then
+            echo "::error::Required vars in Gadi Github Environment are unset."
+            exit 1
+          fi
 
       - name: Set release/prerelease directories
         run: |
           # Check if environment is in list of prerelease environments
-          if [[ '${{ vars.PRERELEASE_ENVIRONMENTS }}' =~ '"${{ env.environment }}"' ]]; then
+          if [[ '${{ vars.PRERELEASE_ENVIRONMENTS }}' =~ '"${{ matrix.environment }}"' ]]; then
             echo "Using prerelease deployment directories"
             echo "CONDA_BASE=${{ vars.PRERELEASE_CONDA_BASE }}" >> $GITHUB_ENV
             echo "ADMIN_DIR=${{ vars.PRERELEASE_ADMIN_DIR }}" >> $GITHUB_ENV
@@ -114,6 +81,16 @@ jobs:
             echo "CONDA_BASE=${{ vars.CONDA_BASE }}" >> $GITHUB_ENV
             echo "ADMIN_DIR=${{ vars.ADMIN_DIR }}" >> $GITHUB_ENV
           fi
+
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Download base container
+        if: inputs.build_and_test
+        uses: actions/download-artifact@v4
+        with:
+            name: base-container
+            path: container
 
       - name: Setup SSH
         uses: access-nri/actions/.github/actions/setup-ssh@main
@@ -124,6 +101,13 @@ jobs:
             ${{ secrets.HOST_DATA }}
           private-key: ${{ secrets.SSH_KEY }}
 
+      - name: Create parent repository directories
+        if: inputs.build_and_test
+        run: |
+          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
+          mkdir -p ${{ secrets.REPO_PATH }}
+          EOT
+
       - name: Sync repository to Gadi
         run: |
           rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
@@ -132,6 +116,7 @@ jobs:
             ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ secrets.REPO_PATH }}
 
       - name: Create Admin dirs on Gadi
+        if: inputs.build_and_test
         run: |
           ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
           set -e
@@ -139,20 +124,21 @@ jobs:
           export CONDA_BASE="${{ env.CONDA_BASE }}"
           export APPS_USERS_GROUP="${{ vars.APPS_USERS_GROUP }}"
           export APPS_OWNER="${{ vars.APPS_OWNER }}"
+          export REPO_PATH="${{ secrets.REPO_PATH }}"
 
-          source "${{ secrets.REPO_PATH }}/scripts/install_config.sh"
-          source "${{ secrets.REPO_PATH }}/scripts/functions.sh"
+          source "${REPO_PATH}"/scripts/install_config.sh
+          source "${REPO_PATH}"/scripts/functions.sh
           mkdir -p "${ADMIN_DIR}" "${JOB_LOG_DIR}" "${BUILD_STAGE_DIR}"
           set_admin_perms "${ADMIN_DIR}" "${JOB_LOG_DIR}" "${BUILD_STAGE_DIR}"
-
           EOT
 
       - name: Build conda environment
+        if: inputs.build_and_test
         run: |
           ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
           set -e
           export SCRIPT_DIR="${{ secrets.REPO_PATH }}/scripts"
-          export CONDA_ENVIRONMENT="${{ env.environment }}"
+          export CONDA_ENVIRONMENT="${{ matrix.environment }}"
           export ADMIN_DIR="${{ env.ADMIN_DIR }}"
           export CONDA_BASE="${{ env.CONDA_BASE }}"
           export APPS_USERS_GROUP="${{ vars.APPS_USERS_GROUP }}"
@@ -171,11 +157,12 @@ jobs:
           EOT
 
       - name: Test conda environment
+        if: inputs.build_and_test
         run: |
           ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
           set -e
           export SCRIPT_DIR="${{secrets.REPO_PATH}}/scripts"
-          export CONDA_ENVIRONMENT="${{ env.environment }}"
+          export CONDA_ENVIRONMENT="${{ matrix.environment }}"
           export ADMIN_DIR="${{ env.ADMIN_DIR }}"
           export CONDA_BASE="${{ env.CONDA_BASE }}"
           export APPS_USERS_GROUP="${{ vars.APPS_USERS_GROUP }}"
@@ -192,13 +179,14 @@ jobs:
             "${SCRIPT_DIR}"/test.sh
 
           EOT
-
+  
       - name: Deploy conda environment
+        if: inputs.deploy
         run: |
           ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
           set -e
           export SCRIPT_DIR="${{ secrets.REPO_PATH }}/scripts"
-          export CONDA_ENVIRONMENT="${{ env.environment }}"
+          export CONDA_ENVIRONMENT="${{ matrix.environment }}"
           export ADMIN_DIR="${{ env.ADMIN_DIR }}"
           export CONDA_BASE="${{ env.CONDA_BASE }}"
           export APPS_USERS_GROUP="${{ vars.APPS_USERS_GROUP }}"
